version: '3'
services:

  web:
    build: .
    image: "mscarceller/practica-ci"
    container_name: "web"
    ports:
      - "8080:8080"
    links:
      - db
  db:
    image: mysql:5.7
    container_name: "db"
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=test
    ports:
      - '3306:3306'
    healthcheck:
        test: "/usr/bin/mysql --user=root --password=pass --execute \"SHOW DATABASES;\""
        interval: 3s
        timeout: 1s
        retries: 5